# Generated by Django 3.1.13 on 2022-06-28 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=500, unique=True)),
                ('company_or_user', models.CharField(max_length=220)),
                ('nos', models.IntegerField(blank=True, default=0, null=True)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
