# Generated by Django 3.1.13 on 2022-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
    ]
