# Generated by Django 3.1.13 on 2022-06-29 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_inventory_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='nos',
            new_name='price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchased_by',
            field=models.CharField(blank=True, choices=[('Ahad', 'Ahad'), ('Siddique', 'Siddique'), ('Sabbir', 'Sabbir')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='company_or_user',
            field=models.CharField(choices=[('Impetus Center', 'Impetus Center'), ('Impetus Office', 'Impetus Office'), ('Impetus Lounge', 'Impetus Lounge'), ('BMS', 'BMS')], max_length=200),
        ),
    ]
