# Generated by Django 3.1.13 on 2022-06-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220629_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
