# Generated by Django 3.1.13 on 2022-06-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220629_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_date',
        ),
    ]
