# Generated by Django 3.1.13 on 2022-06-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_inventory_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='purchase_date',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchased_from',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
