# Generated by Django 3.1.13 on 2022-06-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220629_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('EC10', 'EC10'), ('HDD', 'HDD'), ('IP Camera', 'IP Camera'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('PABX', 'PABX'), ('PoE Switch', 'PoE Switch'), ('RAM', 'RAM'), ('Router', 'Router'), ('SSD', 'SSD'), ('Tab', 'Tab'), ('UPS', 'UPS'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchased_by',
            field=models.CharField(blank=True, choices=[('Ahad', 'Ahad'), ('Sabbir', 'Sabbir'), ('Siddique', 'Siddique')], max_length=50, null=True),
        ),
    ]
