# Generated by Django 3.1.13 on 2022-06-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220629_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, choices=[('CPU', 'CPU'), ('EC10', 'EC10'), ('HDD', 'HDD'), ('IP Camera', 'IP Camera'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('PABX', 'PABX'), ('Pendrive', 'Pendrive'), ('PoE Switch', 'PoE Switch'), ('RAM', 'RAM'), ('Router', 'Router'), ('SSD', 'SSD'), ('Tab', 'Tab'), ('UPS', 'UPS'), ('Other', 'Other')], max_length=200, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
                ('purchased_by', models.CharField(blank=True, choices=[('Ahad', 'Ahad'), ('Sabbir', 'Sabbir'), ('Siddique', 'Siddique')], max_length=50, null=True)),
                ('purchased_from', models.CharField(blank=True, max_length=500, null=True)),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
