# Generated by Django 4.0.5 on 2022-07-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_inventory_price_remove_inventory_purchased_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, choices=[('CPU', 'CPU'), ('EC10', 'EC10'), ('HDD', 'HDD'), ('IP Camera', 'IP Camera'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('PABX', 'PABX'), ('Pendrive', 'Pendrive'), ('Printer', 'Printer'), ('PoE Switch', 'PoE Switch'), ('RAM', 'RAM'), ('Router', 'Router'), ('SSD', 'SSD'), ('Tab', 'Tab'), ('UPS', 'UPS'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
