# Generated by Django 4.0.5 on 2022-08-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_purchase_detail_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=990, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
