# Generated by Django 4.0.5 on 2022-08-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_category_alter_inventory_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_name',
        ),
    ]
