# Generated by Django 3.2.6 on 2023-09-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_purchase_detail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_detail',
            name='purchased_for',
            field=models.CharField(blank=True, choices=[('Impetus Office', 'Impetus Office'), ('Impetus Lounge', 'Impetus Lounge'), ('Impetus Center', 'Impetus Center')], max_length=200, null=True),
        ),
    ]
